server:
  port: 8880
spring:
  datasource:
   name: test
   url: jdbc:mysql://192.168.1.70:3306/kbs
   username: root
   password: kbs123456
   # 使用druid数据源
   driver-class-name: com.mysql.jdbc.Driver
   filters: stat
   maxActive: 20
   initialSize: 1
   maxWait: 60000
   minIdle: 1
   timeBetweenEvictionRunsMillis: 60000
   minEvictableIdleTimeMillis: 300000
   validationQuery: select 'x'
   testWhileIdle: true
   testOnBorrow: false
   testOnReturn: false
   poolPreparedStatements: true
   maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.kbs.base.*